server:
  port: 80

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/graduation_project
    username: root
    password: mysql-123
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 125.124.5.117
    port: 6379
    password: Shuo@134
